### ISSUE TITLE
Logo Proposal for Random Dungeon

### ISSUE THREAD

**Issue by candyskull920** [MusicScore/Random-Dungeon#2]
Hi @MusicScore 
I am an open source enthusiast and I am looking to expand my work portfolio.
I would like to collaborate with your project for free, I can provide you with a logo for your project

Good day
Skull C.

**Comment by MusicScore** [comment]
Hi @candyskull920:

Thank you for your offer!

I know it is not clear from just the README, but my original purpose for this project is to get into the swing of coding. I have no grander goals except to get this to work and have a deeper understanding of how to structure and design a video game, and how to do so in an efficient and optimized way. I have no real intent on publishing it as a game, though anyone is certainly free to build the project for themselves and borrow any segment thereof.

If you still want to contribute a logo knowing this, I will certainly not stop you. I only ask that you are absolutely aware that this project is in no way, shape, or form done professionally, this is entirely done in my free time, and that there will be no monetary or physical compensation for anyone's contributions (including my own) other than a special thanks and a recognition of your work in the README and the game's credits section.

Regards,
MusicScore

**Comment by MusicScore** [comment]
Hi @candyskull920:

As I mentioned before, this is not meant to be released as a professional product. As a result, I have not come up with a name that can be attached to the project. The only information I can offer you is that I wish to have the program randomly generate a dungeon with corridors and rooms (things already done by many other people), and to allow any given user to explore the dungeon in a first-person perspective, perhaps similar exploration-wise to games such as the _Etrian Odyssey_ series and _Labyrinth of Refrain: Coven of Dusk_.

If you are willing to send sample artwork, I would be willing to look over them. Past works that you have done and are able to share will also be appreciated. Be warned that I cannot guarantee that your work will be accepted with the exception of non-malicious code for the sole reason that this project is not, and will not be, a completed video game with the purpose of being distributed to the public.

Regards,
MusicScore

**Comment by candyskull920** [comment]
I will be sending my proposals soon @MusicScore

**Comment by MusicScore** [comment]
Closing.
